name: Build and deploy Shadow

on:
  push:
    branches:
        - dev  # Adjust this as necessary
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
    
          - name: Log in to Docker registry
            uses: docker/login-action@v1
            with:
              registry: https://docker-registry.leorek.dev
              username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
              password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
          - name: Build and push Docker image
            uses: docker/build-push-action@v3
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: docker-registry.leorek.dev/shadow:latest
          
          - name: Deploy to Coolify
            run: | 
              curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

    
